// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grpc_model.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiddlewareInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareInput) Reset() {
	*x = MiddlewareInput{}
	mi := &file_grpc_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareInput) ProtoMessage() {}

func (x *MiddlewareInput) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareInput.ProtoReflect.Descriptor instead.
func (*MiddlewareInput) Descriptor() ([]byte, []int) {
	return file_grpc_model_proto_rawDescGZIP(), []int{0}
}

func (x *MiddlewareInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            float32                `protobuf:"fixed32,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Roles         string                 `protobuf:"bytes,3,opt,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_grpc_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_grpc_model_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetail) GetId() float32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetail) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

var File_grpc_model_proto protoreflect.FileDescriptor

const file_grpc_model_proto_rawDesc = "" +
	"\n" +
	"\x10grpc_model.proto\x12\x04grpc\"'\n" +
	"\x0fMiddlewareInput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"H\n" +
	"\n" +
	"UserDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x02R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x03 \x01(\tR\x05rolesB\x04Z\x02./b\x06proto3"

var (
	file_grpc_model_proto_rawDescOnce sync.Once
	file_grpc_model_proto_rawDescData []byte
)

func file_grpc_model_proto_rawDescGZIP() []byte {
	file_grpc_model_proto_rawDescOnce.Do(func() {
		file_grpc_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_model_proto_rawDesc), len(file_grpc_model_proto_rawDesc)))
	})
	return file_grpc_model_proto_rawDescData
}

var file_grpc_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_model_proto_goTypes = []any{
	(*MiddlewareInput)(nil), // 0: grpc.MiddlewareInput
	(*UserDetail)(nil),      // 1: grpc.UserDetail
}
var file_grpc_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_model_proto_init() }
func file_grpc_model_proto_init() {
	if File_grpc_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_model_proto_rawDesc), len(file_grpc_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_model_proto_goTypes,
		DependencyIndexes: file_grpc_model_proto_depIdxs,
		MessageInfos:      file_grpc_model_proto_msgTypes,
	}.Build()
	File_grpc_model_proto = out.File
	file_grpc_model_proto_goTypes = nil
	file_grpc_model_proto_depIdxs = nil
}
