// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grpc_controller.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpc_controller_proto protoreflect.FileDescriptor

const file_grpc_controller_proto_rawDesc = "" +
	"\n" +
	"\x15grpc_controller.proto\x12\x04grpc\x1a\x10grpc_model.proto2I\n" +
	"\x0eUserController\x127\n" +
	"\n" +
	"Middleware\x12\x15.grpc.MiddlewareInput\x1a\x10.grpc.UserDetail\"\x00B\x04Z\x02./b\x06proto3"

var file_grpc_controller_proto_goTypes = []any{
	(*MiddlewareInput)(nil), // 0: grpc.MiddlewareInput
	(*UserDetail)(nil),      // 1: grpc.UserDetail
}
var file_grpc_controller_proto_depIdxs = []int32{
	0, // 0: grpc.UserController.Middleware:input_type -> grpc.MiddlewareInput
	1, // 1: grpc.UserController.Middleware:output_type -> grpc.UserDetail
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_controller_proto_init() }
func file_grpc_controller_proto_init() {
	if File_grpc_controller_proto != nil {
		return
	}
	file_grpc_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_controller_proto_rawDesc), len(file_grpc_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_controller_proto_goTypes,
		DependencyIndexes: file_grpc_controller_proto_depIdxs,
	}.Build()
	File_grpc_controller_proto = out.File
	file_grpc_controller_proto_goTypes = nil
	file_grpc_controller_proto_depIdxs = nil
}
