version: '3'
services:
  app:
    container_name: codebase
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres
      - redis
    networks:
      - apinetwork
        
  postgres:
    image: postgres:latest
    container_name: db_tokokocak
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: codebase
    volumes:
      - vpostgres:/var/lib/postgresql/data
      - ./db/db-prod:/docker-entrypoint-initdb.d/
    networks:
      - apinetwork

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass konohagakure
    volumes: 
      - cache:/data
    networks:
      - apinetwork
volumes:
  vpostgres:
  cache:

networks:
  apinetwork:
    driver: bridge

    